### ISSUE TITLE
PETSc 3.11.3 error: cannot convert ‘PetscBool’ to ‘PCMGGalerkinType’ for argument ‘2’ to ‘PetscErrorCode PCMGSetGalerkin(PC, PCMGGalerkinType)’

### ISSUE THREAD

**Issue by trandatjp** [topopt/TopOpt_in_PETSc#8]
Hi all,
I am using the newest version of PETSc  for my work.
However I got an error while compiling with a newer version of PETSc3.11.3 as following:
"LinearElasticity.cc:1811:32: error: cannot convert ‘PetscBool’ to ‘PCMGGalerkinType’ for argument ‘2’ to ‘PetscErrorCode PCMGSetGalerkin(PC, PCMGGalerkinType)’
   PCMGSetGalerkin(pc,PETSC_TRUE);"
Can you help me to solve this problem?

Thank you very much,
Best Regards,
Tran Quang Dat.

**Comment by topopt** [comment]
Hi Tran,

The problem is that you are using an old version of the TopOptInPETSc code with a new PETSc release. The PETSc interfaces are changed from time to time, and hence you need to update your code whenever you download a new PETSc version. Below follows three options to remedy your issues:

1. Download the newest version of the TopOptInPETSc from this page.
2. Check your version of the TopOptInPETSc code against the new version. 
3. Check the changelog on the PETSc homepage to see what has changed.

Good luck and hope you have fun with the code!
/niels

**Comment by trandatjp** [comment]
Thank you!

**Comment by trandatjp** [comment]
Hi all,
I am using the PETSc 3.7.7 and want to update to new version of the PETSc 3.11.3.
I checked my code and compared with the new version as your suggested.
Now I got a new error compiling with a newer version of PETSc3.11.3 as following:
" terminate called after throwing an instance of 'std::bad_array_new_length'
terminate called after throwing an instance of 'std::bad_array_new_length'
  what():  std::bad_array_new_length
terminate called after throwing an instance of 'std::bad_array_new_length'
  what():  std::bad_array_new_length
terminate called after throwing an instance of 'std::bad_array_new_length'
  what():  std::bad_array_new_length
terminate called after throwing an instance of 'std::bad_array_new_length'
  what():  std::bad_array_new_length
terminate called after throwing an instance of 'std::bad_array_new_length'
  what():  std::bad_array_new_length
  what():  std::bad_array_new_length"
There is no error when I used the older version PETSc 3.7.7.
Can you help me to solve this problem?

Thank you very much,
Best Regards,
Tran Quang Dat.
