### ISSUE TITLE
Terminate called after throwing an instance of 'std::bad_array_new_length'

### ISSUE THREAD

**Issue by trandatjp** [topopt/TopOpt_in_PETSc#9]
Hi all,
I am using the PETSc 3.7.7 and want to update to new version of the PETSc 3.11.3.
I got an error while compiling with a newer version of PETSc 3.11.3 as following:
" terminate called after throwing an instance of 'std::bad_array_new_length'
terminate called after throwing an instance of 'std::bad_array_new_length'
what(): std::bad_array_new_length
terminate called after throwing an instance of 'std::bad_array_new_length'
what(): std::bad_array_new_length
terminate called after throwing an instance of 'std::bad_array_new_length'
what(): std::bad_array_new_length
terminate called after throwing an instance of 'std::bad_array_new_length'
what(): std::bad_array_new_length
terminate called after throwing an instance of 'std::bad_array_new_length'
what(): std::bad_array_new_length
what(): std::bad_array_new_length"
There was no error when I used the older version PETSc 3.7.7.
Can you help me to solve this problem?

Thank you very much,
Best Regards,
Tran Quang Dat.

**Comment by topopt** [comment]
Hi Tran,

Not sure what your problem is. 

First - check that your PETSc installation works. And if you gace problems, these should be directed at the PETSc developers. See the instructions on https://www.mcs.anl.gov/petsc/miscellaneous/mailing-lists.html

Secondly, download the newest TopOptInPETSc code and build it with PETSc 3.11.X. This will work fine if your PETSc installation is verified.

Good luck,
/niels
